services:
  app:
    image: ghcr.io/karakeep-app/karakeep:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      OLLAMA_BASE_URL: http://ollama:11434
      INFERENCE_TEXT_MODEL: deepseek-r1:1.5b
      INFERENCE_IMAGE_MODEL: minicpm-v
      INFERENCE_CONTEXT_LENGTH: 2048
      INFERENCE_JOB_TIMEOUT_SEC: 300
      CRAWLER_FULL_PAGE_SCREENSHOT: true
      OCR_LANGS: eng, chi_tra, chi_sim
      DATA_DIR: /data
      DISABLE_SIGNUPS: false
    depends_on: 
      - ollama
      - meilisearch
    
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_EDGE_IP_VERSION=auto
    env_file:
      - cloudflared.env

  ollama:
    image: ollama/ollama
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        limits:
          cpus: '4'


volumes:
  meilisearch:
  data:
  ollama:
