services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: ""
      ADMIN_TOKEN: ""
      DISABLE_ADMIN_TOKEN: true
      SIGNUPS_ALLOWED: false
      SIGNUPS_DOMAINS_WHITELIST: grd0.net
    volumes:
      - data:/data/

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    depends_on:
      - vaultwarden
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_EDGE_IP_VERSION=auto
    env_file:
      - cloudflared.env

volumes:
  data:

networks:
  default:
    enable_ipv6: true