services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN}
      ADMIN_TOKEN: ""
      DISABLE_ADMIN_TOKEN: true
      SIGNUPS_ALLOWED: false
      SIGNUPS_DOMAINS_WHITELIST: grd0.net
    volumes:
      - data:/data/

  tailscale:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    hostname: password
    volumes:
      - ${PWD}/tmp:/tmp
    env_file:
      - tailscale.env

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    depends_on:
      - tailscale
      - vaultwarden
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ${PWD}/tmp/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    network_mode:
      service:tailscale

volumes:
  data:

networks:
  default:
    enable_ipv6: true