services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: ""
      ADMIN_TOKEN: ""
      DISABLE_ADMIN_TOKEN: true
      SIGNUPS_ALLOWED: false
      SIGNUPS_DOMAINS_WHITELIST: grd0.net
    volumes:
      - data:/data/

  web:
    image: docker.io/library/nginx
    restart: always
    ports:
      - 8443:443
    depends_on:
      - vaultwarden
    volumes:
      - certs:/etc/ssl/certs:z,ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:z,ro

  self-sign:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=vaultwarden.local
      - CA_SUBJECT=admin@grd0.net
      - SSL_KEY=/certs/vaultwarden.local.key
      - SSL_CSR=/certs/vaultwarden.local.csr
      - SSL_CERT=/certs/vaultwarden.local.crt

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_EDGE_IP_VERSION=6
    env_file:
      - cloudflared.env

volumes:
  data:
  certs:

networks:
  default:
    enable_ipv6: true