services:
  invidious:
    image: quay.io/invidious/invidious:latest
    restart: unless-stopped
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        force_resolve: ipv6
        db:
          dbname: invidious
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          host: invidious-db
          port: 5432
        check_tables: true
        invidious_companion:
        - private_url: "http://companion:8282/companion"
        invidious_companion_key: "${INVIDIOUS_COMPANION_KEY}"
        external_port: 443
        domain: invidious.grd0.net
        https_only: true
        statistics_enabled: false
        use_pubsub_feeds: true
        use_innertube_for_captions: true
        registration_enabled: false
        hmac_key: "${INVIDIOUS_HMAC_KEY}"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/stats || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  materialious:
    image: wardpearce/materialious-full:latest
    restart: unless-stopped
    environment:
      # Secure secret for signing cookies
      # Not required if PUBLIC_INTERNAL_AUTH is false
      COOKIE_SECRET: "${INVIDIOUS_HMAC_KEY}"

      # Database connectiong URI
      # Not required if PUBLIC_INTERNAL_AUTH is false
      # postgresql, mysql2, mariadb & sqlite supported
      # guide here for URL structure https://docs.preset.io/docs/uri-connection-strings
      DATABASE_CONNECTION_URI: "sqlite:///materialious-data/materialious.db"

      # YouTube player id to use, can be left blank but setting to a older player id may fix 
      # video playback with local video processing.
      # https://youtube-player-ids.nadeko.net
      PUBLIC_PLAYER_ID: ""

      # Use Materialious account system.
      PUBLIC_INTERNAL_AUTH: "true"

      # If Auth is required to use this instance.
      # Should be left as true, otherwise anyone can use Materialious proxy.
      PUBLIC_REQUIRE_AUTH: "true"

      # Allow anyone to register
      PUBLIC_REGISTRATION_ALLOWED: "false"

      # Comma-separated list of usernames with admin privileges
      # e.g. "user1,user2"
      PUBLIC_ADMIN_USERNAMES: "maybeken"
      
      # Disable POW Captcha
      PUBLIC_CAPTCHA_DISABLED: "false"

      # Disable rate limiting
      # Not recommended for public instances
      PUBLIC_RATE_LIMIT_DISABLED: "false"
      
      # Allows you to whitelist additional domains in proxy.
      # Should be comma separated and be the base domain
      # e.g. "youtube.com,google.com" NOT "https://youtube.com,https://videos.google.com"
      WHITELIST_BASE_DOMAIN: "grd0.net"
  
      # Specify a path to a certificate to trust, useful when using self-signed certificates.
      PROXY_TRUST_CA: ""

      # Allow any domain in proxy
      # This shouldn't be used unless you KNOW what your doing
      # requires PUBLIC_REGISTRATION_ALLOWED to be false
      # PUBLIC_REQUIRE_AUTH to be true
      # PUBLIC_INTERNAL_AUTH to be true
      # to take effect.
      PUBLIC_DANGEROUS_ALLOW_ANY_PROXY: "false"

      # Optionally set a default Invidious instance
      # This will also whitelist this instance in the proxy.
      PUBLIC_DEFAULT_INVIDIOUS_INSTANCE: ""

      # URL TO RYD (Return YouTube Dislike / https://github.com/Anarios/return-youtube-dislike)
      # Leave blank to disable completely.
      # This will also whitelist this instance in the proxy.
      PUBLIC_DEFAULT_RETURNYTDISLIKES_INSTANCE: "https://returnyoutubedislikeapi.com"

      # URL to Sponsorblock
      # Leave blank to completely disable sponsorblock.
      # This will also whitelist this instance in the proxy.
      PUBLIC_DEFAULT_SPONSERBLOCK_INSTANCE: "https://sponsor.ajay.app"

      # URL to DeArrow
      # This will also whitelist this instance in the proxy.
      PUBLIC_DEFAULT_DEARROW_INSTANCE: "https://sponsor.ajay.app"

      # URL to DeArrow thumbnail instance
      # This will also whitelist this instance in the proxy.
      PUBLIC_DEFAULT_DEARROW_THUMBNAIL_INSTANCE: "https://dearrow-thumb.ajay.app"

      # Look at "Overwriting Materialious defaults" for all the accepted values.
      # This will also whitelist this instance in the proxy.
      PUBLIC_DEFAULT_SETTINGS: '{"themeColor": "#2596be","region": "US"}'

  companion:
    image: quay.io/invidious/invidious-companion:latest
    environment:
      - SERVER_SECRET_KEY=${INVIDIOUS_COMPANION_KEY}
    restart: unless-stopped
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    cap_drop:
      - ALL
    read_only: true
    # cache for youtube library
    volumes:
      - companioncache:/var/tmp/youtubei.js:rw
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:17-alpine
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_EDGE_IP_VERSION=6
    env_file:
      - cloudflared.env

volumes:
  postgresdata:
  companioncache:
  materialious-data:

networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB9::/112
          gateway: 2001:0DB9::1