services:
  mc:
    image: itzg/minecraft-server:java17-alpine
    environment:
      EULA: "TRUE"
      VERSION: 1.20.1
      TYPE: FORGE
      FORGE_VERSION: 47.4.0
      INIT_MEMORY: 3G
      MAX_MEMORY: 8G
      MAX_PLAYERS: "8"
      ICON: "./icon.png"
      OVERRIDE_ICON: "true"
      USE_MEOWICE_FLAGS: "true"
      DIFFICULTY: "2"
      SIMULATION_DISTANCE: "8"
      VIEW_DISTANCE: "8"
      SYNC_CHUNK_WRITES: "false"
      ENABLE_WHITELIST: "true"
      WHITELIST_FILE: "./whitelist.txt"
      PLAYER_IDLE_TIMEOUT: "600"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
    volumes:
      - /mnt/app-data/minecraft/sf5:/data

  playit:
    image: ghcr.io/playit-cloud/playit-agent
    environment:
      - SECRET_KEY=${SECRET_KEY}

networks:
  default:
    enable_ipv6: true