services:
  api:
    image: grd0.net/api
    build:
      context: src/
      dockerfile: api/Dockerfile
    environment:
      LOG_LEVEL: INFO
      DB_PATH: /opt/app/data/api.db
    env_file:
      - api.env
    volumes:
      - ./data/files:/opt/app/data/files
      - data:/opt/app/data
    restart: unless-stopped

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_EDGE_IP_VERSION=auto
    env_file:
      - cloudflared.env

volumes:
  data:

networks:
  default:
    enable_ipv6: true