services:
  api:
    image: grd0.net/api
    build:
      context: src/
      dockerfile: api/Dockerfile
    environment:
      LOG_LEVEL: INFO
      DB_PATH: /opt/app/data/api.db
    env_file:
      - api.env
    volumes:
      - /Users/ken.lam/Git/grd0-site-monorepo/api/data/files:/opt/app/data/files
      - /Users/ken.lam/Git/grd0-site-monorepo/api/data/api.db:/opt/app/data/api.db
    restart: unless-stopped

  self-sign:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=api.grd0.local
      - CA_SUBJECT=admin@grd0.net
      - SSL_KEY=/certs/api.grd0.local.key
      - SSL_CSR=/certs/api.grd0.local.csr
      - SSL_CERT=/certs/api.grd0.local.crt

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - 8443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - certs:/etc/ssl/certs:z,ro
    depends_on:
      - self-sign

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_EDGE_IP_VERSION=auto
    env_file:
      - cloudflared.env

volumes:
  certs:

networks:
  default:
    enable_ipv6: true